# Generated by Django 5.0.3 on 2024-03-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webbuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('npm', models.CharField(max_length=50)),
                ('prodi', models.CharField(max_length=50)),
            ],
        ),
    ]
